
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rails_messaging_development

test: &test
  <<: *default
  database: rails_messaging_test

production:
  <<: *default
  database: rails_messaging_production
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

cucumber:
  <<: *test
